services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    container_name: python_challenge
    network_mode: "host"
    restart: on-failure
    stdin_open: true
    tty: true
